language: php

php:
    - 5.6
    - 7.0

services:
    - mysql

env:
    - DB_HOST=127.0.0.1 DB_DATABASE=yarak DB_USERNAME=root DB_PASSWORD=

before_install:
    - mysql -e "create database IF NOT EXISTS yarak;" -uroot
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - composer install --prefer-source --no-interaction
    - chmod +x install-phalcon.sh
    - ./install-phalcon.sh 3.0.x

install:
    - echo "Download and Install codecept.phar"
    - wget -c -nc --retry-connrefused --tries=0 http://codeception.com/releases/2.2.8/codecept.phar
    - chmod +x codecept.phar
    - php codecept.phar --version

script:
    - php codecept.phar run --no-interaction

cache:
    directories:
        - vendor
